"""Golden charts for cross-validation against Jagannatha Hora (JHora).

PROVENANCE OF THESE VALUES
--------------------------
The expected values below were generated by cross-checking against **PyJHora**
(`jhora` on PyPI) — the Python port of Jagannatha Hora — configured to match
JHora's conventions exactly: sidereal Lahiri / KP ayanamsa, **mean** lunar
nodes, and **true geometric** positions (no aberration / light-deflection,
`FLG_TRUEPOS|FLG_NOABERR|FLG_NOGDEFL`). PyJHora and this engine agree on planet
longitudes to < 0.3 arcsec, on the ascendant to < 12 arcsec, and on every KP
sign/star/sub-lord and nakshatra/pada exactly (verified over a dense sweep).

These are a high-fidelity proxy for the JHora desktop GUI. For a final
gold-standard pass, re-cast each birth in the JHora application itself and
overwrite any value that differs (the arcminute tolerance absorbs the tiny
Moshier-vs-Swiss-`.se1` differences). The test suite asserts agreement to the
**arcminute**; any field left ``None`` is skipped.

NOTE ON VARGAS: only **D9 (Navamsa)** is filled. D9 is convention-independent
(the classical Parashari navamsa equals the cyclic one). The other divisional
charts have competing conventions — this engine uses the classical Parashari
rules, whereas PyJHora's helper uses a uniform "cyclic" rule, so D2/D3/D4/D10/
D12/D24/D30/D40/D45/D60 differ between them. Confirm your JHora's
"varga calculation method" setting and fill those vargas from the GUI if needed.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional

from engine.birth_data import BirthData


@dataclass
class ExpectedChart:
    """Expected values for one (ayanamsa, house-system) casting of a birth.

    All values are decimal-degree sidereal longitudes unless noted. Leave a
    field ``None`` to skip its assertion until you have the reference value.
    """

    # Map graha name -> expected sidereal longitude (deg).
    planet_longitudes: Optional[Dict[str, float]] = None
    # Map graha name -> expected (nakshatra, pada).
    planet_nakshatra_pada: Optional[Dict[str, tuple]] = None
    # Map graha name -> expected KP sub-lord.
    planet_sublords: Optional[Dict[str, str]] = None
    # Expected ascendant longitude (deg).
    ascendant: Optional[float] = None
    # House cusp longitudes, 1-indexed dict {1: deg, ..., 12: deg}.
    cusps: Optional[Dict[int, float]] = None
    # Expected KP cuspal sub-lords {1: "Mercury", ...}.
    cusp_sublords: Optional[Dict[int, str]] = None


@dataclass
class GoldenChart:
    label: str
    birth: BirthData
    notes: str = ""
    vedic: ExpectedChart = field(default_factory=ExpectedChart)   # Lahiri + whole-sign
    kp: ExpectedChart = field(default_factory=ExpectedChart)      # KP + Placidus

    # ---- Phase 2 expectations (computed on the Vedic / Lahiri chart) ----
    # Balance-of-dasha at birth as (lord, years).
    dasha_balance: Optional[tuple] = None
    # Key divisional placements: {"D9": {"Sun": "Leo", ...}}.
    vargas: Optional[Dict[str, Dict[str, str]]] = None


GOLDEN_CHARTS: List[GoldenChart] = [
    # 1) India, no DST, clean +5:30 offset — the simplest baseline.
    GoldenChart(
        label="delhi_1990_noon",
        birth=BirthData(
            year=1990, month=1, day=1, hour=12, minute=0, second=0,
            latitude=28.6139, longitude=77.2090, timezone="Asia/Kolkata",
            name="Delhi 1990 noon",
        ),
        notes="No DST in India; fixed +5:30. Baseline sanity chart.",
        vedic=ExpectedChart(
            planet_longitudes={
                "Sun": 256.86571, "Moon": 306.46549, "Mars": 226.1275,
                "Mercury": 272.0133, "Jupiter": 71.45561, "Venus": 282.52967,
                "Saturn": 261.91721, "Rahu": 294.72641, "Ketu": 114.72641,
            },
            planet_nakshatra_pada={
                "Sun": ("Purva Ashadha", 2), "Moon": ("Dhanishta", 4),
                "Mars": ("Anuradha", 4), "Mercury": ("Uttara Ashadha", 2),
                "Jupiter": ("Ardra", 2), "Venus": ("Shravana", 1),
                "Saturn": ("Purva Ashadha", 3), "Rahu": ("Dhanishta", 1),
                "Ketu": ("Ashlesha", 3),
            },
            ascendant=343.92264,
            cusps={1: 330.0, 2: 0.0, 3: 30.0, 4: 60.0, 5: 90.0, 6: 120.0,
                   7: 150.0, 8: 180.0, 9: 210.0, 10: 240.0, 11: 270.0, 12: 300.0},
        ),
        kp=ExpectedChart(
            planet_longitudes={
                "Sun": 256.96256, "Moon": 306.56234, "Mars": 226.22435,
                "Mercury": 272.11015, "Jupiter": 71.55246, "Venus": 282.62652,
                "Saturn": 262.01406, "Rahu": 294.82327, "Ketu": 114.82327,
            },
            planet_sublords={
                "Sun": "Moon", "Moon": "Moon", "Mars": "Jupiter",
                "Mercury": "Jupiter", "Jupiter": "Saturn", "Venus": "Rahu",
                "Saturn": "Saturn", "Rahu": "Rahu", "Ketu": "Rahu",
            },
            ascendant=344.01949,
            cusps={1: 344.01949, 2: 20.19202, 3: 47.56779, 4: 71.29839,
                   5: 95.70564, 6: 125.20324, 7: 164.01949, 8: 200.19202,
                   9: 227.56779, 10: 251.29839, 11: 275.70564, 12: 305.20324},
            cusp_sublords={1: "Rahu", 2: "Jupiter", 3: "Saturn", 4: "Saturn",
                           5: "Mercury", 6: "Mars", 7: "Jupiter", 8: "Jupiter",
                           9: "Mercury", 10: "Saturn", 11: "Mercury", 12: "Sun"},
        ),
        dasha_balance=("Mars", 0.1056),
        vargas={"D9": {
            "Sun": "Virgo", "Moon": "Scorpio", "Mars": "Scorpio",
            "Mercury": "Capricorn", "Jupiter": "Capricorn", "Venus": "Aries",
            "Saturn": "Libra", "Rahu": "Leo", "Ketu": "Aquarius",
        }},
    ),

    # 2) New York during Eastern Daylight Time — exercises a DST offset.
    GoldenChart(
        label="nyc_1985_edt",
        birth=BirthData(
            year=1985, month=7, day=13, hour=21, minute=30, second=0,
            latitude=40.7128, longitude=-74.0060, timezone="America/New_York",
            name="NYC 1985 EDT",
        ),
        notes="EDT in effect (UTC-4). Verifies DST-aware conversion.",
        vedic=ExpectedChart(
            planet_longitudes={
                "Sun": 87.91717, "Moon": 41.9366, "Mars": 89.15379,
                "Mercury": 114.45836, "Jupiter": 291.01069, "Venus": 44.72848,
                "Saturn": 207.92647, "Rahu": 21.22044, "Ketu": 201.22044,
            },
            planet_nakshatra_pada={
                "Sun": ("Punarvasu", 3), "Moon": ("Rohini", 1),
                "Mars": ("Punarvasu", 3), "Mercury": ("Ashlesha", 3),
                "Jupiter": ("Shravana", 4), "Venus": ("Rohini", 2),
                "Saturn": ("Vishakha", 3), "Rahu": ("Bharani", 3),
                "Ketu": ("Vishakha", 1),
            },
            ascendant=288.96685,
            cusps={1: 270.0, 2: 300.0, 3: 330.0, 4: 0.0, 5: 30.0, 6: 60.0,
                   7: 90.0, 8: 120.0, 9: 150.0, 10: 180.0, 11: 210.0, 12: 240.0},
        ),
        kp=ExpectedChart(
            planet_longitudes={
                "Sun": 88.01402, "Moon": 42.03346, "Mars": 89.25064,
                "Mercury": 114.55521, "Jupiter": 291.10754, "Venus": 44.82534,
                "Saturn": 208.02332, "Rahu": 21.31729, "Ketu": 201.31729,
            },
            planet_sublords={
                "Sun": "Venus", "Moon": "Rahu", "Mars": "Sun",
                "Mercury": "Rahu", "Jupiter": "Venus", "Venus": "Jupiter",
                "Saturn": "Venus", "Rahu": "Jupiter", "Ketu": "Jupiter",
            },
            ascendant=289.0637,
            cusps={1: 289.0637, 2: 336.96711, 3: 13.19865, 4: 38.87868,
                   5: 60.12074, 6: 81.53202, 7: 109.0637, 8: 156.96711,
                   9: 193.19865, 10: 218.87868, 11: 240.12074, 12: 261.53202},
            cusp_sublords={1: "Mercury", 2: "Mercury", 3: "Mercury", 4: "Venus",
                           5: "Mercury", 6: "Jupiter", 7: "Ketu", 8: "Mercury",
                           9: "Mercury", 10: "Venus", 11: "Ketu", 12: "Jupiter"},
        ),
        dasha_balance=("Moon", 8.5475),
        vargas={"D9": {
            "Sun": "Gemini", "Moon": "Aries", "Mars": "Gemini",
            "Mercury": "Aquarius", "Jupiter": "Cancer", "Venus": "Taurus",
            "Saturn": "Gemini", "Rahu": "Libra", "Ketu": "Aries",
        }},
    ),

    # 3) Pre-DB-era India via an EXPLICIT fixed offset — robustness for old
    #    births where IANA history may be uncertain. (Indian independence.)
    GoldenChart(
        label="midnight_1947_fixed_offset",
        birth=BirthData(
            year=1947, month=8, day=15, hour=0, minute=0, second=0,
            latitude=28.6139, longitude=77.2090, timezone=5.5,
            name="1947-08-15 00:00 +5:30",
        ),
        notes="Fixed numeric offset path; no reliance on IANA historical data.",
        vedic=ExpectedChart(
            planet_longitudes={
                "Sun": 117.99464, "Moon": 93.98375, "Mars": 67.46352,
                "Mercury": 103.68637, "Jupiter": 205.88032, "Venus": 112.57348,
                "Saturn": 110.48052, "Rahu": 35.06972, "Ketu": 215.06972,
            },
            planet_nakshatra_pada={
                "Sun": ("Ashlesha", 4), "Moon": ("Pushya", 1),
                "Mars": ("Ardra", 1), "Mercury": ("Pushya", 4),
                "Jupiter": ("Vishakha", 2), "Venus": ("Ashlesha", 2),
                "Saturn": ("Ashlesha", 2), "Rahu": ("Krittika", 3),
                "Ketu": ("Anuradha", 1),
            },
            ascendant=37.73227,
            cusps={1: 30.0, 2: 60.0, 3: 90.0, 4: 120.0, 5: 150.0, 6: 180.0,
                   7: 210.0, 8: 240.0, 9: 270.0, 10: 300.0, 11: 330.0, 12: 0.0},
        ),
        kp=ExpectedChart(
            planet_longitudes={
                "Sun": 118.09149, "Moon": 94.0806, "Mars": 67.56037,
                "Mercury": 103.78322, "Jupiter": 205.97718, "Venus": 112.67034,
                "Saturn": 110.57737, "Rahu": 35.16658, "Ketu": 215.16658,
            },
            planet_sublords={
                "Sun": "Saturn", "Moon": "Saturn", "Mars": "Rahu",
                "Mercury": "Rahu", "Jupiter": "Ketu", "Venus": "Moon",
                "Saturn": "Venus", "Rahu": "Mercury", "Ketu": "Saturn",
            },
            ascendant=37.82912,
            cusps={1: 37.82912, 2: 63.4381, 3: 86.64517, 4: 111.55011,
                   5: 141.71089, 6: 178.78613, 7: 217.82912, 8: 243.4381,
                   9: 266.64517, 10: 291.55011, 11: 321.71089, 12: 358.78613},
            cusp_sublords={1: "Venus", 2: "Venus", 3: "Venus", 4: "Venus",
                           5: "Jupiter", 6: "Saturn", 7: "Ketu", 8: "Sun",
                           9: "Ketu", 10: "Venus", 11: "Jupiter", 12: "Saturn"},
        ),
        dasha_balance=("Saturn", 18.0732),
        vargas={"D9": {
            "Sun": "Pisces", "Moon": "Leo", "Mars": "Sagittarius",
            "Mercury": "Scorpio", "Jupiter": "Taurus", "Venus": "Capricorn",
            "Saturn": "Capricorn", "Rahu": "Aquarius", "Ketu": "Leo",
        }},
    ),
]
